local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Fuzzy find files' })
vim.keymap.set('n', '<leader>fg', builtin.git_files, { desc = 'Fuzzy find files in git project' })
vim.keymap.set('n', '<leader>fr', builtin.lsp_references, { desc = 'Fuzzy find references' })
vim.keymap.set('n', '<leader>fd', builtin.diagnostics, { desc = 'Fuzzy find diagnostics' })
vim.keymap.set('n', '<leader>fs', function()
	builtin.grep_string({ search = vim.fn.input(">>> ") })
end, { desc = 'Grep in project' })
vim.keymap.set('n', '<leader>?', ':Telescope keymaps<CR>', { desc = 'Open my keymaps in telescope' })
